# Generated by Django 5.0.6 on 2024-06-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('qualifications', models.TextField()),
                ('job_outlook', models.TextField()),
                ('pathways', models.TextField()),
            ],
        ),
    ]
