# Generated by Django 5.0.6 on 2024-06-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('counselor', 'Counselor'), ('admin', 'Admin')], default='student', max_length=10),
        ),
    ]
